---

version: "3"

services:
  mysql:
    image: mysql:5.7.24
    environment:
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: warehouse_test
      MYSQL_ROOT_PASSWORD: warehouse
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
